 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_lachevauchee_fantastique_graphique;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author bapti
 */
public class PageAcceuil extends javax.swing.JFrame {

    public PageAcceuil() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Facile = new javax.swing.JButton();
        Moyen = new javax.swing.JButton();
        Difficile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        regles = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Facile.setText("Facile");
        Facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacileActionPerformed(evt);
            }
        });
        getContentPane().add(Facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 278, -1, -1));

        Moyen.setText("Moyen");
        Moyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoyenActionPerformed(evt);
            }
        });
        getContentPane().add(Moyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        Difficile.setText("Difficle ");
        Difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifficileActionPerformed(evt);
            }
        });
        getContentPane().add(Difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        regles.setColumns(20);
        regles.setLineWrap(true);
        regles.setRows(5);
        regles.setText("Bienvenue dans Light Off !\n\nLe but du jeu est simple : réussir à avoir un tableau entièrement jaune.\nPour ce faire, tu peux activer des lignes, des colonnes ou une diagonale. \nAttention, cela change la couleur de chacune des pièces de la ligne\nsélectionnée.\n\nTu as le choix entre 3 niveaux de difficulté, ou la taille de la grille, \nle nombre de coups et le temps changent ( le temps démarre lorsque\nvous activer votre première cellule).\n\nBonne chance !\n\nVisualiser les caractéristiques des niveaux en cliquant sur les boutons");
        jScrollPane2.setViewportView(regles);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 300, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_lachevauchee_fantastique_graphique/Photo Page.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacileActionPerformed
      Facile f = new Facile();
         f.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_FacileActionPerformed

    private void MoyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoyenActionPerformed
         Moyen f = new Moyen();
         f.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MoyenActionPerformed

    private void DifficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifficileActionPerformed
         Difficile f = new Difficile();
         f.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_DifficileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Difficile;
    private javax.swing.JButton Facile;
    private javax.swing.JButton Moyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea regles;
    // End of variables declaration//GEN-END:variables
}

